### ISSUE TITLE
Sepa xml file

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/l10n-italy#116]
I am porting modules to send/receive xml files to/from banks.
Since February, 1st 2016 files CBI will be no more valid and companies shall use new xml format file.

In order to avoid data duplicate, I would like to use models by Italian localization.
I can't find company cuc that is called "Codice SIA" in italian nomenclature.
Could someone address me to find this field?

TIA

**Comment by antoniov** [comment]
I found "codice_sia" in l10n_it_ricevute_bancarie module.
Is it possible declare this field in some base module, because it should be use by:
- Sepa SCP (aka bonifico bancario SEPA)
- Sepa SDD (aka addebito su conto)
- RiBA (this feature still remain unchanged)

Thanks

**Comment by eLBati** [comment]
It makes sense.
Porting RiBa to 8.0 is still work in progress: https://github.com/OCA/l10n-italy/pull/115
So, we can remove that field from riba module, create ```l10n_it_sia``` and make ```l10n_it_ricevute_bancarie``` depend on ```l10n_it_sia```.
Could you provide a PR for that?

**Comment by antoniov** [comment]
Yes, I could but I have no experience with right flow.
I think I should:
1) Clone project (both branch V7 and V8)
2) Update source with PEP8 (if needed)
3) Make update
4) Issue a PR

Is it right flow?

**Comment by eLBati** [comment]
See [Basic Branching and Merging](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) guide.
In this case, you can start branching 8.0 branch in order to add ```l10n_it_sia``` module (see  the [README](https://github.com/OCA/maintainer-tools/tree/master/template/module) template) and make a PR (see [Using pull requests](https://help.github.com/articles/using-pull-requests/)) to merge your branch into 8.0.
Then, you can post a comment on https://github.com/OCA/l10n-italy/pull/115, so that we can decide how to proceed

**Comment by antoniov** [comment]
Thanks.
I will read that documents and then I wil try to operate.
May ask you about, if I will meet some trouble?

**Comment by eLBati** [comment]
Sure, please consider joining us on IRC freenode channels #oca and #odoo-it (http://www.odoo-italia.org/index.php/community-la-comunita-openerp/chat)
