### ISSUE TITLE
[12]l10n_it_withholding_tax doesn't work for payment multi invoice

### ISSUE THREAD

**Issue by budiiskandar11** [OCA/l10n-italy#1321]
Hello, your withholding_tax module is suitable for my country, it's great.. but it doesn't work for payment multi invoice.

does anyone has fix this problem ?

Thanks

**Comment by eLBati** [comment]
Hi @budiiskandar11 
could you describe step by step how to reproduce the problem?

**Comment by batalhadematos** [comment]
Hello everyone,
I also found this module a great tool for my country.
Unfortunately I have found the same problem as @budiiskandar11.
The module is not working as expected when we try to pay several invoices with WT Withholding included.

The workflow:
- I setup one "WT Withholding" tax with 10%;
- I issued 2 invoices for the same Vendor of a total amount of 1.000,00 each. Since both invoices have a WT Withholding tax of 10%, I should pay my Vendor a total of 1.800,00 (900,00 for each invoice). In this case, 1.800,00 is the real amount I received on cash/bank and it should be the value to be entered on payment window.
- When I select both invoices and register the payment of 1.800,00, one of the invoices is not fully reconciled and the payment information is all messed up.

Please check the attached images.
![WT1](https://user-images.githubusercontent.com/1798270/62339117-d8816000-b4d2-11e9-9bfb-b0501bfada85.png)
![WT2](https://user-images.githubusercontent.com/1798270/62339137-dc14e700-b4d2-11e9-9d7a-c885e212b300.png)

Thank you all very much

Best regards

**Comment by eLBati** [comment]
> When I select both invoices and register the payment of 1.800,00, one of the invoices is not fully reconciled and the payment information is all messed up

Do you register the payment using bank statement?

**Comment by eLBati** [comment]
Found now https://github.com/OCA/l10n-italy/issues/1399 , thanks

**Comment by batalhadematos** [comment]
Thank you @eLBati,
The payment for the multi invoices is made under "Action" menu from the Vendor Bills. 
Workflow:
1- Invoicing | Supplier | Vendor Bills
2- Make 2 invoices with WT included
3- On Vendor Bills list view, select both bills and under "**Action**" menu select "**Register payment**".
4- Enter the value to be paid for 2 invoices.

Invoice 1: Total value: 1000,00 / WT amount: 100,00 / Net to Pay: 900,00
Invoice 2: Total value: 1000,00 / WT Amount: 100,00 / Net to Pay: 900,00

So, on step 4 I enter "1800,00" to be paid since this is the exact amount to be paid to supplier (net to pay from both invoices).

Thank you
Paulo
