### ISSUE TITLE
Fiscal year closing unified for Italy and Spain

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-italy#245]
I think we should join forces for making an unified fiscal year closing for v9. Are you working on the migration now?

**Comment by eLBati** [comment]
@pedrobaeza I am not aware of efforts on that module.
The last working version is for 7.0 and we, at AgileBG, don't use it. We encourage the use of the standard procedure.
I don't know if someone else is interested on it.
@OpenCode @andrea4ever @dcorio  ?

**Comment by sergiocorato** [comment]
We at SimplERP use it (almost) as-is for 8.0, available to help

**Comment by zeroincombenze** [comment]
I use both standard and Fiscal year closing.  I made pep8 of this module on 8.0 and I generated thei PR
https://github.com/OCA/l10n-italy/pull/244/files
I documented it (in italian) here:
http://wiki.zeroincombenze.org/it/Odoo/7.0/man/FI/chiusura2

I can help you, if you agreed

**Comment by alessandrocamilli** [comment]
We use the Fiscal year closing standard.
Now openforce has made a PR with porting to v8 from 7
https://github.com/OCA/l10n-italy/pull/248
Avaible for help

**Comment by antespi** [comment]
We have working on an OCA/account-closing addon in order to have a base addon ready to be inherited in each localization. Each localization will configure by default its account mappings for each LP, NLP, closing and opening moves.

Here is the branch (WIP): https://github.com/Tecnativa/account-closing/tree/account_fiscalyear_closing/account_fiscalyear_closing

We have almost finished development, only test and migration scripts from 8.0 are in TODO list. You can test it in your v9, but you'll need OCA/account-financial-tools/account_reversal from this PR https://github.com/OCA/account-financial-tools/pull/405

We will propose this branch when account_reversal were merged

**Comment by zeroincombenze** [comment]
Hello,
I tried to write regression tests, before doing any change but I had too 
less time to do this.
Your work is very good, I like it.

Thanks & Congrats

*
zeroincombenze® *

SHS-AV Antonio M. Vigliotti
  (Presidente & Chief Technical Officer)

*SHS-AV s.r.l. *(impresa innovativa)
Via Domodossola, 64 - 10145 TORINO - ITALY
*Tel. (+39) 011.0566929*
www.shs-av.com
PEC amministrazione@pec.shs-av.com

Il 05/10/2016 23:15, Antonio Espinosa ha scritto:

**Comment by sergiocorato** [comment]
chiudo per inattività
