### ISSUE TITLE
16.0l10n_italy_fatturapa_attachment_out

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#4025]
Buongiorno,

Nella normativa dell'agenzia dell'entrada sono previsti i campi che non abbiamo trovato nell file XML creato da ODOO.
Per cortesia, esiste un parametro per attivare i campi?
Grazie.
![image](https://github.com/OCA/l10n-italy/assets/48922995/13f7669d-1668-41c6-8796-4621138dd003)

**Comment by SirAionTech** [comment]
Credo sia duplicata di https://github.com/OCA/l10n-italy/issues/4005, puoi verificare?
Se lo è per favore chiudi, grazie

**Comment by matteoopenf** [comment]
Ciao,Per la parte dei dati del ddt c’è un modulo mai mergiato che sopperisce alla richiesta.La pr è in draft se ben ricordo Matteo ***@***.*** Il giorno 8 mar 2024, alle ore 10:33, Marcio Lopes de Mello e Silva ***@***.***> ha scritto:﻿
Buongiorno,
Nella normativa dell'agenzia dell'entrada sono previsti i campi che non abbiamo trovato nell file XML creato da ODOO.
Per cortesia, esiste un parametro per attivare i campi?
Grazie.
image.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano
