### ISSUE TITLE
missing access right on user group Accounting / Auditor

### ISSUE THREAD

**Issue by MC-ChenDi** [OCA/l10n-italy#4144]
## Module
all E-invoice module.

## Describe the bug
missing access right on user group Accounting / Auditor, a  Accounting / Auditor can not open any bill or invoice

## To Reproduce
Odoo 14.0+e (Enterprise Edition)

1. set a user as Accounting / Auditor
2. open any bill o invoice 
3.

**Expected behavior**
Error for opening bill or invoice
![image](https://github.com/OCA/l10n-italy/assets/166132586/f7549d71-1e21-473a-82cb-4cd7c7e6edc5)

**Additional context**
to resolved the problem, need add those access right to auditor
[res.groups (1) (1).xlsx](https://github.com/OCA/l10n-italy/files/15365529/res.groups.1.1.xlsx)

**Comment by SirAionTech** [comment]
Hi,
the PR https://github.com/OCA/l10n-italy/pull/4194 has recently been merged and has fixed some access right issues, could you please check if this issue is still present?

If it's not fixed, please give more detailed steps to reproduce the issue because right now I am not able to reproduce it with only
> 1. set a user as Accounting / Auditor
> 2. open any bill o invoice

For instance, how was the bill/invoice created?

**Comment by MC-ChenDi** [comment]
Ciao Simone, 
siccome siamo migrato già sul 14, quindi non so se lastversione abbia gia risolto il problema. in ogni caso l'errore è semplicemente dovuto a mancanza di diritto di accesso al gruppo accouting/ auditor , avevo caricato in allegati tutti i diritti mancanti
