### ISSUE TITLE
non si carica sulla versione community

### ISSUE THREAD

**Issue by LianaSempi** [OCA/l10n-italy#4333]
Non riesco a caricare il modulo su Odoo community su server linux. Ho provato anche su runbot e mi da questo errore "Nota: è possibile importare solo moduli dati (file .xml e asset statici)" permetto che non sono molto pratica. Grazie

Ma in ogni caso non riesco ad importare nulla sicuramente farò io qualcosa di sbagliato.
scarico il file zip carico con importa direttamente in odoo. 
Grazie mille

**Comment by matteoopenf** [comment]
Puoi descrivere meglio cosa fai e mettere qualche screen?Matteo ***@***.*** Il giorno 24 ago 2024, alle ore 23:38, LianaSempi ***@***.***> ha scritto:﻿
Non riesco a caricare il modulo su Odoo community su server linux. Ho provato anche su runbot e mi da questo errore "Nota: è possibile importare solo moduli dati (file .xml e asset statici)" permetto che non sono molto pratica. Grazie
Ma in ogni caso non riesco ad importare nulla sicuramente farò io qualcosa di sbagliato.
scarico il file zip carico con importa direttamente in odoo.
Grazie mille

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano

**Comment by francesco-ooops** [comment]
Ciao @LianaSempi , questa è una richiesta di supporto generico che non mi sembra relativa ai moduli della community italiana, pertanto chiudo 

ti consiglio di rivolgere la domanda sul nostro server [discord](https://discord.gg/YtVuXGS2) o sul [forum](https://www.odoo-italia.org/forum/forum-1) :)
