### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#734]
i have a mageia 6.x, and i have tried to install this package in odoo, without success .
What i have done :  
i have download the package and unzipped it in the folder l10n-italy-12.0
i have copied the folder in /usr/lib/python2.7/site-package/odoo/addons/
#su -  password   
#service odoo restart
from odoo by advanced administrations , have reload app list.

but without output about 

after have tried to copy any single folder inside l10n-italy-12.0   in  /usr/lib/python2.7/site-package/odoo/addons/
and
#su -  password   
#service odoo restart
from odoo by advanced administrations , have reload app list.

but without output about 
what's my error?
enrico

**Comment by eLBati** [comment]
OCA modules are all available on pypi. So, in order to install, for example, `l10n_it_fatturapa`, the following command is enough:
`pip install --pre odoo12-addon-l10n-it-fatturapa`

`--pre` is needed to make sure to retrieve the last version available, even if not versioned as standard release.

Anyway, I suggest to build your own [requirements file](https://pip.pypa.io/en/stable/user_guide/#requirements-files), to control versions.

**Comment by bitit-it** [comment]
i have this output : 
[root@localhost ~]# pip install --pre odoo12-addon-l10n-it-fatturapa
Collecting odoo12-addon-l10n-it-fatturapa
  Could not find a version that satisfies the requirement odoo12-addon-l10n-it-fatturapa (from versions: )
No matching distribution found for odoo12-addon-l10n-it-fatturapa
